### ISSUE TITLE
Apollo bench

### ISSUE THREAD

**Issue by prasshantg** [Apollo-LMMs/Apollo#2]
Is there a plan to release ApolloBench?

**Comment by orrzohar** [comment]
Hi @prasshantg 
I have made ApolloBench public:

https://huggingface.co/datasets/Apollo-LMMs/ApolloBench

I will be putting in a PR to lmms-eval later today. 

Best,
Orr

**Comment by prasshantg** [comment]
Appreciate it @orrzohar  Looking forward to the lmms-eval PR.

**Comment by orrzohar** [comment]
I am almost done, should put in the PR in the next 48hrs after I test it with a few models

**Comment by whu125** [comment]
Sorry，but why the url [](https://huggingface.co/datasets/Apollo-LMMs/ApolloBench) is 404
