### ISSUE TITLE
Config files error

### ISSUE THREAD

**Issue by LeeChuh** [Apollo-LMMs/Apollo#5]
Thank you for your great work! We plan to evaluate your models on our benchmark. However, while following the steps on GitHub, I encountered the following error:

> ValueError: The model class you are passing has a config_class attribute that is not consistent with the config class you passed (model has None and you passed <class 'transformers_modules.Apollo-7B-t32.configuration_apollo.ApolloConfig'>. Fix one of those so they match!

I’m wondering if this issue could be related to a missing or null entry in the config.json file of the model? Any guidance would be greatly appreciated. 

Could you also clarify what `clip_sampling_ratio` represents? It seems that this ratio is not explained in the paper.

Minor: you don't have a `setup.py`, `pip install -e .` might not work properly here.

**Comment by orrzohar** [comment]
Hi @LeeChuh,
1. Loading model works with snapshot_download, but not without it at the moment. you probably are getting this error by trying to use the AutoModelForCausalLM directly
2.  `clip_sampling_ratio` is the % of the context window that you want to populate (at most) with video tokens
3. fixed. ty!

**Comment by LeeChuh** [comment]
Thank you for your response. I am copying the code directly from your repo and used `snapshpt_download` to load the model, but I still get the same error.

**Comment by halninekilo** [comment]
Same here

`env\Lib\site-packages\transformers\models\auto\auto_factory.py", line 584, in register
    raise ValueError(
ValueError: The model class you are passing has a `config_class` attribute that is not consistent with the config class you passed (model has None and you passed <class 'transformers_modules.8779d04b1ec450b2fe7dd44e68b0d6f38dfc13ec.configuration_apollo.ApolloConfig'>. Fix one of those so they match!`

**Comment by orrzohar** [comment]
I did notice that I did not have a pyproject.toml, I added mine. Could you try re-initializing your env? This could be a huggingface version issue. This script works for our Huggingface Demo as well, so should be functional

**Comment by LeeChuh** [comment]
Thanks, using the new `pyproject.toml` works now!
